version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
    networks:
      - NETWORK
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  electricity_distribution:
    container_name: electricity_distribution
    build: .
    image: electricity_distribution
    environment:
      - POSTGRES_URL=postgres:5432
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=postgres
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - "8081:8081"
    networks:
      - NETWORK

  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - NETWORK
    volumes:
      - zookeeper


  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - NETWORK
    volumes:
      - kafka

volumes:
  postgres:
    external: true
  zookeeper:
    name: zookeeper
    external: false
  kafka:
    name: kafka
    external: false

networks:
  NETWORK:
    name: NETWORK
    driver: bridge
    external: true
